" /etc/vimrc

" Ensure defaults are set before customizing settings, not after
source $VIMRUNTIME/defaults.vim

let skip_defaults_vim=1 

set nocompatible
set backspace=2
set mouse=
set tabstop=4
set shiftwidth=4
set expandtab
set ruler

syntax on

if (&term == "xterm") || (&term == "putty")
  set background=dark
endif

" End /etc/vimrc
